version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "postgres"
    ports: 
      - "8080:8080"
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - database_postgres:/var/lib/postgresql/data 

  go:
    container_name: go
    build: 
      context: .
    ports: 
      - "5000:5000"
    depends_on:
      - db
  

volumes: 
  database_postgres:
